version: '3.8'

services:
  cafe-pos-system:
    image: vandysodanheang/cafe-pos-system:latest
    container_name: cafe-pos-system
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: production
      RAILS_MASTER_KEY: ''
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: cafe_pos_production
      DB_USERNAME: postgres
      DB_PASSWORD: password
    volumes:
      - ./log:/rails/log
      - ./tmp:/rails/tmp
      - ./storage:/rails/storage
    depends_on:
      - db

  db:
    image: postgres
    container_name: cafe-pos-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cafe_pos_production
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: