name: Release Cafe POS System

on:
  release:
    types: [published]

jobs:
  build:
    name: release-cafe-pos-system
    runs-on: ubuntu-latest
    steps:
      - name: "GIT: Checkout Action Version"
        uses: actions/checkout@v3

      - name: "DOCKER: Authentication with Docker HUB"
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.DOCKER_HUB_URL }}
          username: ${{ vars.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: "DOCKER: Setting Up Docker BuildX"
        uses: docker/setup-buildx-action@v2

      - name: "DOCKER: Setting Up QEMU"
        uses: docker/setup-qemu-action@v2

      - name: "DOCKER: Build Nightly Tag and Push Image to Docker HUB"
        if: "github.event.release.prerelease"
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64/v8
          push: true
          build-args: |
            APP_NAME=${{ vars.REPOSITORY_NAME }}
            APP_VERSION=${{ github.event.release.tag_name }}
            RAILS_MASTER_KEY=${{ secrets.RAILS_MASTER_KEY }}
          tags: |
            ${{ vars.DOCKER_HUB_USERNAME }}/${{ vars.REPOSITORY_NAME }}:nightly
            ${{ vars.DOCKER_HUB_USERNAME }}/${{ vars.REPOSITORY_NAME }}:${{ github.event.release.tag_name }}

      - name: "DOCKER: Build Latest Tag and Push Image to Docker HUB"
        if: "!github.event.release.prerelease"
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            APP_NAME=${{ vars.REPOSITORY_NAME }}
            APP_VERSION=${{ github.event.release.tag_name }}
            RAILS_MASTER_KEY=${{ secrets.RAILS_MASTER_KEY }}
          tags: |
            ${{ vars.DOCKER_HUB_USERNAME }}/${{ vars.REPOSITORY_NAME }}:latest
            ${{ vars.DOCKER_HUB_USERNAME }}/${{ vars.REPOSITORY_NAME }}:${{ github.event.release.tag_name }}